---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check if connection still works
      ansible.builtin.ping:

  roles:
    - role: ansible-role-upgrade
      upgrade_packages:
        - bash
