---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if connection still works
      ansible.builtin.ping:

  roles:
    - role: robertdebock.upgrade
      upgrade_packages:
        - bash
